#!/bin/bash

echo "💬 Slack Webhook Setup Guide"
echo "============================"
echo ""
echo "Follow these steps to set up Slack notifications:"
echo ""
echo "1. Go to https://api.slack.com/apps"
echo "2. Click 'Create New App' → 'From scratch'"
echo "3. Give it a name like 'Paper Monitor'"
echo "4. Select your workspace"
echo "5. Click 'Create App'"
echo ""
echo "6. In the left sidebar, click 'Incoming Webhooks'"
echo "7. Toggle 'Activate Incoming Webhooks' to On"
echo "8. Click 'Add New Webhook to Workspace'"
echo "9. Choose the channel where you want notifications"
echo "10. Click 'Allow'"
echo "11. Copy the webhook URL (starts with https://hooks.slack.com/services/...)"
echo ""
echo "12. Update your config.json:"
echo "    - Set 'slack.enabled' to true"
echo "    - Paste your webhook URL in 'slack.webhook_url'"
echo "    - Set your preferred channel in 'slack.channel'"
echo ""
echo "13. For GitHub Actions, add the webhook URL as a secret:"
echo "    - Go to your repository Settings → Secrets and variables → Actions"
echo "    - Add 'SLACK_WEBHOOK_URL' with your webhook URL"
echo ""
echo "The monitor will send notifications like:"
echo "📚 Found 15 new papers!"
echo ""
echo "*SFM* (5 papers):"
echo "• Paper Title 1"
echo "  _by Author 1 and Author 2_"
echo "• Paper Title 2"
echo "  _by Author 3 and 2 others_" 