#!/bin/bash

echo "🚀 GitHub Repository Setup Guide"
echo "================================"
echo ""
echo "Follow these steps to deploy your paper monitor to GitHub:"
echo ""
echo "1. Go to https://github.com/new"
echo "2. Create a new repository named 'academic-paper-monitor'"
echo "3. Make it PUBLIC (required for GitHub Pages)"
echo "4. DO NOT initialize with README, .gitignore, or license"
echo "5. Click 'Create repository'"
echo ""
echo "After creating the repository, run these commands:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/academic-paper-monitor.git"
echo "git push -u origin main"
echo ""
echo "Then enable GitHub Pages:"
echo "1. Go to repository Settings → Pages"
echo "2. Set source to 'Deploy from a branch'"
echo "3. Select 'gh-pages' branch"
echo "4. Click 'Save'"
echo ""
echo "Finally, set up GitHub Actions secrets:"
echo "1. Go to repository Settings → Secrets and variables → Actions"
echo "2. Add 'SLACK_WEBHOOK_URL' with your Slack webhook URL"
echo "3. The GITHUB_TOKEN is automatically provided"
echo ""
echo "Your site will be available at:"
echo "https://YOUR_USERNAME.github.io/academic-paper-monitor/"
echo ""
echo "The GitHub Actions workflow will run daily at 9 AM UTC"
echo "and automatically deploy updates to GitHub Pages." 